// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1damKZbA8IqWd31h5HLuEbvVyRktyMJM',
    appId: '1:119304652646:web:babb3317d256e051a12aa7',
    messagingSenderId: '119304652646',
    projectId: 'oprecppb',
    authDomain: 'oprecppb.firebaseapp.com',
    databaseURL: 'https://oprecppb-default-rtdb.firebaseio.com',
    storageBucket: 'oprecppb.appspot.com',
    measurementId: 'G-BSXN6DZEKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaRG_PI59t6WtusRsDJyBwhgSgsaPRMJk',
    appId: '1:119304652646:android:55cca640e34d9897a12aa7',
    messagingSenderId: '119304652646',
    projectId: 'oprecppb',
    databaseURL: 'https://oprecppb-default-rtdb.firebaseio.com',
    storageBucket: 'oprecppb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYF-ZckpBW72qweohur3V4NbNiPzjphX0',
    appId: '1:119304652646:ios:c027b956d0845b21a12aa7',
    messagingSenderId: '119304652646',
    projectId: 'oprecppb',
    databaseURL: 'https://oprecppb-default-rtdb.firebaseio.com',
    storageBucket: 'oprecppb.appspot.com',
    iosBundleId: 'com.example.tes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYF-ZckpBW72qweohur3V4NbNiPzjphX0',
    appId: '1:119304652646:ios:9b84036fb11fa54ea12aa7',
    messagingSenderId: '119304652646',
    projectId: 'oprecppb',
    databaseURL: 'https://oprecppb-default-rtdb.firebaseio.com',
    storageBucket: 'oprecppb.appspot.com',
    iosBundleId: 'com.example.tes.RunnerTests',
  );
}
